### ISSUE TITLE
`/apps/whale-api`: module.model

### ISSUE THREAD

**Issue by ivan-zynesis** [DeFiCh/jellyfish#1247]
#### What would you like to be added:
- migrate from existing code base from https://github.com/DeFiCh/whale/tree/main/src/module.model
- add missing unit test / spec accordingly

#### Why is this needed (check list):
- [ ]  _hex.encoder
- [ ] _model.probes
- [ ] _module
- [ ] block
- [ ] masternode.stats
- [ ] masternode
- [ ] oracle.history
- [ ] oracle.price.active
- [ ] oracle.price.aggregated.interval
- [ ] oracle.price.aggregated
- [ ] oracle.price.feed
- [ ] oracle.token.currency
- [ ] oracle
- [ ] pool.pair.history
- [ ] pool.pair.token
- [ ] pool.swap.aggregated
- [ ] pool.swap
- [ ] price.ticker
- [ ] raw.block
- [ ] script.activity
- [ ] script.aggregation
- [ ] script.unspent
- [ ] token
- [ ] transaction
- [ ] transction.vin
- [ ] tranction.vout
- [ ] vault.auction.batch.history

**Comment by ivan-zynesis** [comment]
@kodemon I am starting this by branching out from https://github.com/DeFiCh/jellyfish/pull/1239

**Comment by kodemon** [comment]
@ivan-zynesis just want to mention that https://github.com/DeFiCh/jellyfish/pull/1239 is being discontinued in favor of going back to the original migration https://github.com/DeFiCh/jellyfish/pull/1005 to lessen the impact. Any further refactoring being relegated to new tickets once we get whale ported.

**Comment by ivan-zynesis** [comment]
> @ivan-zynesis just want to mention that #1239 is being discontinued in favor of going back to the original migration #1005 to lessen the impact of refactoring, fixing, migrating and reviewing. Any further refactoring being relegated to new tickets once we get whale ported.

#1239 looks like a direct migration, is it conflicting with #1005 ?

**Comment by kodemon** [comment]
Currently https://github.com/DeFiCh/jellyfish/pull/1201 and https://github.com/DeFiCh/jellyfish/pull/1239 is refactoring file names and file structures as part of apps/whale-api migration efforts. Where as https://github.com/DeFiCh/jellyfish/pull/1005 keeps everything as is from whale except for required updates to imports because of path mismatch between jellyfish and whales typescript and jest setup.

After some conversations on this topic yesterday, it was decided to go back to the original porting efforts as it would not require additional extensive reviews of the file refactoring.

The resolution currently is to port whale with minimal code and file structure changes, and then create new tickets for refactoring and anything else we may want to do post migration.

**Comment by ivan-zynesis** [comment]
Migration will be done by script first #1248
Test reinforcement to be added later.
