### ISSUE TITLE
Enhancement Request: Playground to have loan token balances for easy top up

### ISSUE THREAD

**Issue by pierregee** [DeFiCh/jellyfish#1311]
#### What would you like to be added:
- Allow top up of of loan tokens

According to a brief discussion with @canonbrother, it's feasible to create a master vault that will contain all the loan tokens.. and easy to accounttoaccount (topup). 

 @canonbrother Thanks for explaining how it works in the jellyfish side 🙏 

#### Why is this needed:
In light wallet, we have **Top up 10 { token }** which uses `sendtokenstoaddress`. 

This is extensively used when testing in playground and more importantly, in our e2e tests. The e2e tests takes a longer time topping up loan tokens because we need to manually `create a vault` -> `borrow loan token` -> `use it to pay for another loan`

<img width="805" alt="image" src="https://user-images.githubusercontent.com/13292662/161469987-657337c1-a9a8-4e78-b1c6-13250950d544.png">

This is the error we're receiving
![image](https://user-images.githubusercontent.com/13292662/161469355-f380f1ef-fe01-4214-9b97-0b35fcf6b274.png)

**Comment by canonbrother** [comment]
the `sendtokenstoaddress` doesn't work due to insufficient balance on loan token
![image](https://user-images.githubusercontent.com/8097901/161480984-75361bd0-5d9c-4e6c-a462-b619923dc13e.png)

To minimize the changes on light wallet.. we can remain to use `sendtokenstoaddress`, the pg behind just increase the loan amount from the "master" vault that we ady have
