### ISSUE TITLE
Migrate salmon into the jellyfish monorepo

### ISSUE THREAD

**Issue by monstrobishi** [DeFiCh/jellyfish#652]
#### What would you like to be added:

Migrate all of salmon's packages into the jellyfish monorepo.

#### Why is this needed:

Faster iteration and less overhead on dependency management

**Comment by monstrobishi** [comment]
Some questions:

- Do we move the lambda packaging e.g. `npm run package` from the top level package.json to the lambda functions package.json, or do we combine the CI/etc at the root?
- Do we keep the e2e workflow, will this slow down jellyfish deployment, how will we structure this and other CI components as part of jellyfish (similar to above)

**Comment by fuxingloh** [comment]
1. Yeah we need to keep the `packaging` workflow, when we move whale and playground, there will be a packaging for them.
2. Yup I updated the narrative https://github.com/DeFiCh/jellyfish#end-to-end-testing

I think for safety best to just re-run and rebuild everything since that's the only way to ensure consistency.

**Comment by fuxingloh** [comment]
Over the weekend, I realize the DeFiCh/whale project, which is a critical component has to be migrated before we can effectively migrate salmon to jellyfish. 

Initially, I wanted to delay salmon migration until we have the whale project on DeFiCh/jellyfish.

However, the more I think about it, having salmon in a silo is unnecessarily unhealthy. We will do it regardless and have `whale-api-client` being used fixed to a static version. After we migrate the entire whale project over then we point it to local deps.

**Comment by fuxingloh** [comment]
I spent another great deal of time thinking about the salmon project yesterday. 

It can’t be within the `jellyfish` project, as jellyfish is a library/server project it doesn't have the necessary ops pipeline to guarantee the quality. It has to be a standalone `project`, as it is today, and run like a product project with the many ops pipeline.

Everything else is still required but it can't be part of `DeFiCh/jellyfish` because it needs more ops pipeline than jellyfish and the ops requirement scopes beyond jellyfish setup.

**Comment by fuxingloh** [comment]
moved to another repo
